/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommitmentRouteImport } from './routes/commitment'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PillarsRouteImport } from './routes/pillars'
import { Route as TheoryOfChangeRouteImport } from './routes/theory-of-change'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentRoute = CommitmentRouteImport.update({
  id: '/commitment',
  path: '/commitment',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsRoute = PillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryOfChangeRoute = TheoryOfChangeRouteImport.update({
  id: '/theory-of-change',
  path: '/theory-of-change',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commitment': typeof CommitmentRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/partners': typeof PartnersRoute
  '/pillars': typeof PillarsRoute
  '/theory-of-change': typeof TheoryOfChangeRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commitment': typeof CommitmentRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/partners': typeof PartnersRoute
  '/pillars': typeof PillarsRoute
  '/theory-of-change': typeof TheoryOfChangeRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commitment': typeof CommitmentRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/partners': typeof PartnersRoute
  '/pillars': typeof PillarsRoute
  '/theory-of-change': typeof TheoryOfChangeRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commitment'
    | '/gallery'
    | '/impact'
    | '/partners'
    | '/pillars'
    | '/theory-of-change'
    | '/vision-mission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commitment'
    | '/gallery'
    | '/impact'
    | '/partners'
    | '/pillars'
    | '/theory-of-change'
    | '/vision-mission'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commitment'
    | '/gallery'
    | '/impact'
    | '/partners'
    | '/pillars'
    | '/theory-of-change'
    | '/vision-mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommitmentRoute: typeof CommitmentRoute
  GalleryRoute: typeof GalleryRoute
  ImpactRoute: typeof ImpactRoute
  PartnersRoute: typeof PartnersRoute
  PillarsRoute: typeof PillarsRoute
  TheoryOfChangeRoute: typeof TheoryOfChangeRoute
  VisionMissionRoute: typeof VisionMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitment': {
      id: '/commitment'
      path: '/commitment'
      fullPath: '/commitment'
      preLoaderRoute: typeof CommitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars': {
      id: '/pillars'
      path: '/pillars'
      fullPath: '/pillars'
      preLoaderRoute: typeof PillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory-of-change': {
      id: '/theory-of-change'
      path: '/theory-of-change'
      fullPath: '/theory-of-change'
      preLoaderRoute: typeof TheoryOfChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommitmentRoute: CommitmentRoute,
  GalleryRoute: GalleryRoute,
  ImpactRoute: ImpactRoute,
  PartnersRoute: PartnersRoute,
  PillarsRoute: PillarsRoute,
  TheoryOfChangeRoute: TheoryOfChangeRoute,
  VisionMissionRoute: VisionMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
